version: '3.5'

services:
  sever:
    container_name: sever
    restart: always
    build: sever
    volumes:
      - ./sever:/usr/src/app
    networks:
      - net_work
  web:
    container_name: web
    restart: always
    build: web
    volumes:
      - ./web:/usr/src/app

    networks:
      - net_work
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' 
      - '443:443' 
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE_NPM}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - net_work

  db:
    container_name: db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NPM}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql/proxy_host.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net_work
    command: ["mariadb --user=root --password=admin npm < /docker-entrypoint-initdb.d/init.sql"]
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

    networks:
      - net_work

networks:
  net_work:
    driver: bridge
