version: '3.5'

services:
  sever:
    container_name: sever
    restart: always
    build: src/sever
    volumes:
      - ./src/sever:/usr/src/app
    networks:
      - net_work
      
  web:
    container_name: web
    restart: always
    build: src/web
    volumes:
      - ./src/web:/usr/src/app
    networks:
      - net_work

  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' 
      - '443:443' 
      - '81:81'
    volumes:
      - ./nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - net_work

  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - net_work
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - net_work

networks:
  net_work:
    driver: bridge
