version: '3.5'

services:
  socket:
    container_name: socket
    restart: always
    build: src/socket
    volumes:
      - ./src/socket:/usr/src/app
    networks:
      - backend
      
  web:
    container_name: web
    restart: always
    build: src/web
    volumes:
      - ./src/web:/usr/src/app
    networks:
      - backend

  auth:
    container_name: auth
    restart: always
    build: src/authen
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE_NAME}
    volumes:
      - ./src/authen:/usr/src/app
    networks:
      - backend
     

  api:
    container_name: api
    restart: always
    build: src/apiCRUD
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE_NAME}
    volumes:
      - ./src/apiCRUD:/usr/src/app
    networks:
      - backend

   
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - web
      - auth
      - socket
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - fontend
      - backend


  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - backend

networks:
  fontend:
    driver: bridge
  backend:
    driver: bridge
