version: '3.5'

services:
# ===============================   Reverse Proxy   =============================
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx_init/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - fontend
      - backend

# =================================  Node Js  =======================================
  socket:
    container_name: socket
    restart: always
    build: src/socket
    volumes:
      - ./src/socket:/usr/src/app
    networks:
      - backend
      

  web:
    container_name: web
    restart: always
    build: src/web
    environment:
      - SESSIONKEY=${SESSIONKEY}
    volumes:
      - ./src/web:/usr/src/app
    networks:
      - backend


  auth:
    container_name: auth
    restart: always
    build: src/authen
    volumes:
      - ./src/authen:/usr/src/app
    environment:
      - HOST=${HOST}
      - EMAIL=${EMAIL}
      - PASS=${PASS}
      - SERVICE=${SERVICE}
    networks:
      - backend

  userimg:
    container_name: userimg
    restart: always
    build: src/userimage
    volumes:
      - ./src/userimage:/usr/src/app
    networks:
      - backend

  api:
    container_name: api
    restart: always
    build: src/apiCRUD
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE_NAME}
    volumes:
      - ./src/apiCRUD:/usr/src/app
    networks:
      - backend
      - dbNetwork

   
# =================================  Database  =======================================
  authredis:
    container_name: authredis
    restart: always
    image: redis
    networks:
      - backend
      
  db:
    container_name: db
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbNetwork


# =================================  Monitor   =======================================
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    volumes:
      - ./redisinsight:/db
    ports:
      - '8001:8001'
    networks:
      - backend
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    networks:
      - dbNetwork

    
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - fontend
      - backend
      - dbNetwork


# =============================================================================

networks:
  fontend:
    driver: bridge
  backend:
    driver: bridge
  dbNetwork:
    driver: bridge
